customhost = "mydatabase.ci4td1u42qon.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "mydatabase"
custombucket = "	my-newproject-bucket-123"
customregion = "us-east-1"
